services:
    sonata.admin.post:
        class: Acme\PostBundle\Admin\PostAdmin
        tags:
                    - name: sonata.admin
                      manager_type: orm
                      group: "acme.admin.group.content"
                      label: "acme.admin.model.post"
                      label_catalogue: "AcmePostBundle"
        arguments:
            - ~
            - Acme\PostBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AcmePostBundle]]