Acme\PostBundle\Entity\Post:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        body:
            type: text
        created:
            type: datetime
        updated:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ persistCreatedDatetime, updateUdatedDatetime ]
        preUpdate: [ updateUdatedDatetime ]

